/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classe;

import javax.swing.JOptionPane;

/**
 *
 * @author alber
 */
public class NotaSwing extends javax.swing.JFrame {
    nome n = new nome();
    
    /**
     * Creates new form NotaSwing
     */
    public NotaSwing() {
        initComponents();
        n.setNome();
        notaRecuperacao.setVisible(false);
        valorRecuperacao.setVisible(false);
        lblResultado.setVisible(false);
        lblMedia.setVisible(false);
        jOptionPane1.setVisible(false);
        btnRecu.setVisible(false);
        btnReset.setVisible(false);
        lblAluno.setVisible(false);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        nota2 = new javax.swing.JLabel();
        nota1 = new javax.swing.JLabel();
        nota4 = new javax.swing.JLabel();
        nota3 = new javax.swing.JLabel();
        notaRecuperacao = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        valor1 = new javax.swing.JTextField();
        valor2 = new javax.swing.JTextField();
        valor3 = new javax.swing.JTextField();
        valor4 = new javax.swing.JTextField();
        valorRecuperacao = new javax.swing.JTextField();
        lblResultado = new javax.swing.JLabel();
        lblMedia = new javax.swing.JLabel();
        jOptionPane1 = new javax.swing.JOptionPane();
        btnRecu = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblAluno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/asd-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        nota2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nota2.setText("Nota do 2°Bimestre:");
        getContentPane().add(nota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        nota1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nota1.setText("Nota do 1° Bimestre:");
        getContentPane().add(nota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        nota4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nota4.setText("Nota do 4°Bimestre:");
        getContentPane().add(nota4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        nota3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nota3.setText("Nota do 3°Bimestre:");
        getContentPane().add(nota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        notaRecuperacao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        notaRecuperacao.setText("Nota de Recuperação:");
        getContentPane().add(notaRecuperacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        btnCalcular.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 160, 80));
        getContentPane().add(valor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 80, -1));
        getContentPane().add(valor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 80, -1));
        getContentPane().add(valor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 80, -1));
        getContentPane().add(valor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 80, -1));
        getContentPane().add(valorRecuperacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 90, -1));

        lblResultado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(51, 51, 255));
        lblResultado.setText("Resultado Aqui");
        getContentPane().add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        lblMedia.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMedia.setText("Media:");
        getContentPane().add(lblMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));
        getContentPane().add(jOptionPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        btnRecu.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnRecu.setText("Calcular");
        btnRecu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuActionPerformed(evt);
            }
        });
        getContentPane().add(btnRecu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 160, 80));

        btnReset.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        btnReset.setText("<html>Novo Aluno</html");
        btnReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 160, 80));

        lblAluno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAluno.setText("Aluno");
        getContentPane().add(lblAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        float n1 = Float.parseFloat(valor1.getText());
        float n2 = Float.parseFloat(valor2.getText());
        float n3 = Float.parseFloat(valor3.getText());
        float n4 = Float.parseFloat(valor4.getText());
        float media = (n1 + n2 + n3 + n4)/4;
        
        lblAluno.setVisible(true);
        lblAluno.setText("Aluno: " + n.getNome());
        if(media >= 7){
            lblMedia.setText(("Media: " + Float.toString(media)));
            lblResultado.setText("Aprovado!");
            lblResultado.setVisible(true);
            lblMedia.setVisible(true);
            btnReset.setVisible(true);                      
        }else{
            lblMedia.setText(("Media: " + Float.toString(media)));
            lblResultado.setText("Você foi para prova final!");
            lblResultado.setVisible(true);
            lblMedia.setVisible(true);
            jOptionPane1.showMessageDialog(null, "Digite sua nota de recuperação!");
            nota1.setVisible(false);
            nota2.setVisible(false);
            nota3.setVisible(false);
            nota4.setVisible(false);
            valor1.setVisible(false);
            valor2.setVisible(false);
            valor3.setVisible(false);
            valor4.setVisible(false);
            notaRecuperacao.setVisible(true);
            valorRecuperacao.setVisible(true);
            btnCalcular.setVisible(false);
            btnRecu.setVisible(true);
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnRecuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuActionPerformed
        // TODO add your handling code here:
        float recupe = Float.parseFloat(valorRecuperacao.getText());
        if (recupe >= 6){
            lblMedia.setText(("Nota de Recuperação " + Float.toString(recupe)));
            lblResultado.setText("Passou de ano!");
            btnReset.setVisible(true);
        }else{
            lblMedia.setText(("Nota de Recuperação " + Float.toString(recupe)));
            lblResultado.setText("Reprovou de Ano");
            btnReset.setVisible(true);
        }
    }//GEN-LAST:event_btnRecuActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        notaRecuperacao.setVisible(false);
        valorRecuperacao.setVisible(false);
        lblResultado.setVisible(false);
        lblMedia.setVisible(false);
        jOptionPane1.setVisible(false);
        btnRecu.setVisible(false);
        btnReset.setVisible(false);
        nota1.setVisible(true);
        nota2.setVisible(true);
        nota3.setVisible(true);
        nota4.setVisible(true);
        valor1.setVisible(true);
        valor2.setVisible(true);
        valor3.setVisible(true);
        valor4.setVisible(true);
        btnCalcular.setVisible(true);
        valor1.setText("");
        valor2.setText("");
        valor3.setText("");
        valor4.setText("");
        lblAluno.setVisible(false);
        n.setNome();
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotaSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotaSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnRecu;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JLabel lblAluno;
    private javax.swing.JLabel lblMedia;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel nota1;
    private javax.swing.JLabel nota2;
    private javax.swing.JLabel nota3;
    private javax.swing.JLabel nota4;
    private javax.swing.JLabel notaRecuperacao;
    private javax.swing.JTextField valor1;
    private javax.swing.JTextField valor2;
    private javax.swing.JTextField valor3;
    private javax.swing.JTextField valor4;
    private javax.swing.JTextField valorRecuperacao;
    // End of variables declaration//GEN-END:variables
}
